const DOCS = [
 {id:1,name:'04 Synth se.pdf',type:'PDF',level:'2ème Année',mod:'Synthèse',date:'2025',size:'260 KB',cat:'synthese',content:'Document PDF — 2ème Année — Synthèse'},
 {id:2,name:'2ème SC 3.docx',type:'DOCX',level:'4ème Année Sciences',mod:'Général',date:'2025',size:'169 KB',cat:'cours',content:'Document DOCX — 4ème Année Sciences — Général'},
 {id:3,name:'2ème Sciences 4.docx',type:'DOCX',level:'4ème Année Sciences',mod:'Général',date:'2025',size:'24 KB',cat:'cours',content:'Document DOCX — 4ème Année Sciences — Général'},
 {id:4,name:'2Lettres 1.docx',type:'DOCX',level:'2ème Année',mod:'Général',date:'2025',size:'25 KB',cat:'cours',content:'Document DOCX — 2ème Année — Général'},
 {id:5,name:'4ème année Lettres.docx',type:'DOCX',level:'4ème Année Lettres',mod:'Général',date:'2025',size:'40 KB',cat:'cours',content:'Document DOCX — 4ème Année Lettres — Général'},
 {id:6,name:'À la lumière de la raison 2.doc',type:'DOC',level:'3ème Année Lettres',mod:'Raison et Lumières',date:'2025',size:'36 KB',cat:'cours',content:'Document DOC — 3ème Année Lettres — Raison et Lumières'},
 {id:7,name:'A-la-lumière-de-la-raison-Essai-bac-2017-Correction.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Dissertation',date:'2025',size:'16 KB',cat:'cours',content:'Document DOCX — 3ème Année Lettres — Dissertation'},
 {id:8,name:'bac les tonalités.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Tonalités',date:'2025',size:'40 KB',cat:'cours',content:'Document DOCX — 3ème Année Lettres — Tonalités'},
 {id:9,name:'Bac-blanc_Poesie_proposition-de-correction_dissertation.doc',type:'DOC',level:'3ème Année Lettres',mod:'Poésie',date:'2025',size:'38 KB',cat:'cours',content:'Document DOC — 3ème Année Lettres — Poésie'},
 {id:10,name:'BATRANU_2017_diffusion.pdf',type:'PDF',level:'3ème Année Lettres',mod:'Général',date:'2025',size:'3401 KB',cat:'cours',content:'Document PDF — 3ème Année Lettres — Général'},
 {id:11,name:'bibliothèque-de-classe.docx',type:'DOCX',level:'4ème Année Lettres',mod:'Lecture',date:'2025',size:'15 KB',cat:'cours',content:'Document DOCX — 4ème Année Lettres — Lecture'},
 {id:12,name:'Biographie de Simone de Beauvoir.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Général',date:'2025',size:'16 KB',cat:'cours',content:'Document DOCX — 3ème Année Lettres — Général'},
 {id:13,name:'BULTIN DE NOTE.xlsx',type:'XLSX',level:'Non classé',mod:'Général',date:'2025',size:'12 KB',cat:'cours',content:'Document XLSX — Non classé — Général'},
 {id:14,name:'comment argumenter.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Général',date:'2025',size:'25 KB',cat:'cours',content:'Document DOCX — 3ème Année Lettres — Général'},
 {id:15,name:'Compréhension.docx',type:'DOCX',level:'2ème Année',mod:'Compréhension',date:'2025',size:'16 KB',cat:'cours',content:'Document DOCX — 2ème Année — Compréhension'},
 {id:16,name:'con_tps_ind_11Concordance.pdf',type:'PDF',level:'2ème Année',mod:'Conjugaison',date:'2025',size:'58 KB',cat:'cours',content:'Document PDF — 2ème Année — Conjugaison'},
 {id:17,name:'concordance des temps.Bac.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Conjugaison',date:'2025',size:'21 KB',cat:'cours',content:'Document DOCX — 3ème Année Lettres — Conjugaison'},
 {id:18,name:'conjugaison.docx',type:'DOCX',level:'2ème Année',mod:'Conjugaison',date:'2025',size:'17 KB',cat:'cours',content:'Document DOCX — 2ème Année — Conjugaison'},
 {id:19,name:'Correction du devoir de synthèse III.docx',type:'DOCX',level:'2ème Année',mod:'Contrôle',date:'2025',size:'17 KB',cat:'controle',content:'Document DOCX — 2ème Année — Contrôle'},
 {id:20,name:'cours-photoshop.docx',type:'DOCX',level:'Non classé',mod:'Général',date:'2025',size:'302 KB',cat:'cours',content:'Document DOCX — Non classé — Général'},
 {id:21,name:'DC1-2Sc-3-2017-2018-Je-suis-rentrèe-au-lycée.docx',type:'DOCX',level:'2ème Année',mod:'Général',date:'2025',size:'22 KB',cat:'controle',content:'Document DOCX — 2ème Année — Général'},
 {id:22,name:'DC2-la-femme-2-inf-2-B-H-2017-1.doc',type:'DOC',level:'2ème Année',mod:'Femme et Société',date:'2025',size:'40 KB',cat:'controle',content:'Document DOC — 2ème Année — Femme et Société'},
 {id:23,name:'demain-tout-commence-fiche-pedagogique-du-film-fiche-pedagogique-regarder-une-video_98230.doc',type:'DOC',level:'4ème Année Lettres',mod:'Général',date:'2025',size:'1528 KB',cat:'fiche',content:'Document DOC — 4ème Année Lettres — Général'},
 {id:24,name:'dev 1.docx',type:'DOCX',level:'2ème Année',mod:'Contrôle',date:'2025',size:'15 KB',cat:'controle',content:'Document DOCX — 2ème Année — Contrôle'},
 {id:25,name:'dev 1s11 mod 4.docx',type:'DOCX',level:'1ère Année',mod:'Contrôle',date:'2025',size:'15 KB',cat:'controle',content:'Document DOCX — 1ère Année — Contrôle'},
 {id:26,name:'dev 2ème L mod3.docx',type:'DOCX',level:'2ème Année',mod:'Contrôle',date:'2025',size:'16 KB',cat:'controle',content:'Document DOCX — 2ème Année — Contrôle'},
 {id:27,name:'dev 2ème mod 5.docx',type:'DOCX',level:'2ème Année',mod:'Contrôle',date:'2025',size:'16 KB',cat:'controle',content:'Document DOCX — 2ème Année — Contrôle'},
 {id:28,name:'dev 2ème.docx',type:'DOCX',level:'2ème Année',mod:'Contrôle',date:'2025',size:'22 KB',cat:'controle',content:'Document DOCX — 2ème Année — Contrôle'},
 {id:29,name:'dev 4ème L Mod 1.docx',type:'DOCX',level:'4ème Année Lettres',mod:'Contrôle',date:'2025',size:'18 KB',cat:'controle',content:'Document DOCX — 4ème Année Lettres — Contrôle'},
 {id:30,name:'dev bac.doc',type:'DOC',level:'3ème Année Lettres',mod:'Contrôle',date:'2025',size:'76 KB',cat:'controle',content:'Document DOC — 3ème Année Lettres — Contrôle'},
 {id:31,name:'dev bac.pdf',type:'PDF',level:'3ème Année Lettres',mod:'Contrôle',date:'2025',size:'576 KB',cat:'controle',content:'Document PDF — 3ème Année Lettres — Contrôle'},
 {id:32,name:'dev cont2 2ème L.docx',type:'DOCX',level:'2ème Année',mod:'Contrôle',date:'2025',size:'20 KB',cat:'controle',content:'Document DOCX — 2ème Année — Contrôle'},
 {id:33,name:'dev controle 1-2ème-lettres.doc',type:'DOC',level:'2ème Année',mod:'Contrôle',date:'2025',size:'66 KB',cat:'controle',content:'Document DOC — 2ème Année — Contrôle'},
 {id:34,name:'dev mod 1 2ème.docx',type:'DOCX',level:'2ème Année',mod:'Contrôle',date:'2025',size:'26 KB',cat:'controle',content:'Document DOCX — 2ème Année — Contrôle'},
 {id:35,name:'dev mod3.docx',type:'DOCX',level:'2ème Année',mod:'Contrôle',date:'2025',size:'13 KB',cat:'controle',content:'Document DOCX — 2ème Année — Contrôle'},
 {id:36,name:'dev syn 2ème Lettres.1+2.docx',type:'DOCX',level:'2ème Année',mod:'Contrôle',date:'2025',size:'19 KB',cat:'controle',content:'Document DOCX — 2ème Année — Contrôle'},
 {id:37,name:'dev syn 2ème Lettres.docx',type:'DOCX',level:'2ème Année',mod:'Contrôle',date:'2025',size:'17 KB',cat:'controle',content:'Document DOCX — 2ème Année — Contrôle'},
 {id:38,name:'dev syn 3 2ème année.docx',type:'DOCX',level:'2ème Année',mod:'Contrôle',date:'2025',size:'21 KB',cat:'controle',content:'Document DOCX — 2ème Année — Contrôle'},
 {id:39,name:'dev syn1 2ème sc.docx',type:'DOCX',level:'4ème Année Sciences',mod:'Contrôle',date:'2025',size:'26 KB',cat:'controle',content:'Document DOCX — 4ème Année Sciences — Contrôle'},
 {id:40,name:'dev synt 1 bac lettres 2.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Contrôle',date:'2025',size:'18 KB',cat:'controle',content:'Document DOCX — 3ème Année Lettres — Contrôle'},
 {id:41,name:'Dev-cont1-4è-letttres.docx',type:'DOCX',level:'4ème Année Lettres',mod:'Général',date:'2025',size:'34 KB',cat:'cours',content:'Document DOCX — 4ème Année Lettres — Général'},
 {id:42,name:'dev-Femmes-sté.docx',type:'DOCX',level:'2ème Année',mod:'Femme et Société',date:'2025',size:'43 KB',cat:'cours',content:'Document DOCX — 2ème Année — Femme et Société'},
 {id:43,name:'devoir 1s10 mod4.docx',type:'DOCX',level:'1ère Année',mod:'Contrôle',date:'2025',size:'23 KB',cat:'controle',content:'Document DOCX — 1ère Année — Contrôle'},
 {id:44,name:'devoir 2019.docx',type:'DOCX',level:'2ème Année',mod:'Contrôle',date:'2025',size:'18 KB',cat:'controle',content:'Document DOCX — 2ème Année — Contrôle'},
 {id:45,name:'devoir 2ème mod 3.docx',type:'DOCX',level:'2ème Année',mod:'Contrôle',date:'2025',size:'21 KB',cat:'controle',content:'Document DOCX — 2ème Année — Contrôle'},
 {id:46,name:'devoir 2ème mod amour.docx',type:'DOCX',level:'2ème Année',mod:'Contrôle',date:'2025',size:'21 KB',cat:'controle',content:'Document DOCX — 2ème Année — Contrôle'},
 {id:47,name:'devoir bac lettres mod 3.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Contrôle',date:'2025',size:'26 KB',cat:'controle',content:'Document DOCX — 3ème Année Lettres — Contrôle'},
 {id:48,name:'devoir c 1 2ème sciences 4.docx',type:'DOCX',level:'4ème Année Sciences',mod:'Contrôle',date:'2025',size:'28 KB',cat:'controle',content:'Document DOCX — 4ème Année Sciences — Contrôle'},
 {id:49,name:'devoir contrôle 1 bac L.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Contrôle',date:'2025',size:'20 KB',cat:'controle',content:'Document DOCX — 3ème Année Lettres — Contrôle'},
 {id:50,name:'DEVOIR DE CONTROLE N° 1 francais mr Titty.pdf',type:'PDF',level:'1ère Année',mod:'Contrôle',date:'2025',size:'168 KB',cat:'controle',content:'Document PDF — 1ère Année — Contrôle'},
 {id:51,name:'Devoir de Contrôle N°1 - Français - Bac Economie & Gestion (2016-2017) Mr Megbli-converti.docx',type:'DOCX',level:'Non classé',mod:'Contrôle',date:'2025',size:'59 KB',cat:'controle',content:'Document DOCX — Non classé — Contrôle'},
 {id:52,name:'Devoir de Contrôle N°1 - Français - Bac Technique (2016-2017) Mr Megbli Tarek-converti.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Contrôle',date:'2025',size:'195 KB',cat:'controle',content:'Document DOCX — 3ème Année Lettres — Contrôle'},
 {id:53,name:'Devoir de Contrôle N°2 - Français - 2ème Sciences (2013-2014) Mme SAAD (1).pdf',type:'PDF',level:'4ème Année Sciences',mod:'Contrôle',date:'2025',size:'108 KB',cat:'controle',content:'Document PDF — 4ème Année Sciences — Contrôle'},
 {id:54,name:'devoir de synthèse bac lettres 2.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Contrôle',date:'2025',size:'20 KB',cat:'controle',content:'Document DOCX — 3ème Année Lettres — Contrôle'},
 {id:55,name:'devoir guerre.docx',type:'DOCX',level:'2ème Année',mod:'Contrôle',date:'2025',size:'19 KB',cat:'controle',content:'Document DOCX — 2ème Année — Contrôle'},
 {id:56,name:'Devoir mod3 2ème.docx',type:'DOCX',level:'2ème Année',mod:'Contrôle',date:'2025',size:'26 KB',cat:'controle',content:'Document DOCX — 2ème Année — Contrôle'},
 {id:57,name:'devoir modernité.pdf',type:'PDF',level:'3ème Année Lettres',mod:'Modernité',date:'2025',size:'245 KB',cat:'controle',content:'Document PDF — 3ème Année Lettres — Modernité'},
 {id:58,name:'devoir synthèse 1-4ème L2.docx',type:'DOCX',level:'4ème Année Lettres',mod:'Contrôle',date:'2025',size:'19 KB',cat:'controle',content:'Document DOCX — 4ème Année Lettres — Contrôle'},
 {id:59,name:'devoir synthèse 2ème.docx',type:'DOCX',level:'2ème Année',mod:'Contrôle',date:'2025',size:'18 KB',cat:'controle',content:'Document DOCX — 2ème Année — Contrôle'},
 {id:60,name:'devoir-2eme-travail (1).docx',type:'DOCX',level:'2ème Année',mod:'Contrôle',date:'2025',size:'18 KB',cat:'controle',content:'Document DOCX — 2ème Année — Contrôle'},
 {id:61,name:'devoir-4-ème-Souad-Amour.docx',type:'DOCX',level:'2ème Année',mod:'Contrôle',date:'2025',size:'19 KB',cat:'controle',content:'Document DOCX — 2ème Année — Contrôle'},
 {id:62,name:'Devoir-de-contrôle-1bac-lettres.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Contrôle',date:'2025',size:'16 KB',cat:'controle',content:'Document DOCX — 3ème Année Lettres — Contrôle'},
 {id:63,name:'Devoir-de-contrôle-3-pour-la-1ère-A-2.docx',type:'DOCX',level:'1ère Année',mod:'Contrôle',date:'2025',size:'18 KB',cat:'controle',content:'Document DOCX — 1ère Année — Contrôle'},
 {id:64,name:'devoir-évasion-rêve-dêtre-sur-scène-1 (1).docx',type:'DOCX',level:'2ème Année',mod:'Contrôle',date:'2025',size:'20 KB',cat:'controle',content:'Document DOCX — 2ème Année — Contrôle'},
 {id:65,name:'Devoir-femme-et-société 1.docx',type:'DOCX',level:'2ème Année',mod:'Femme et Société',date:'2025',size:'27 KB',cat:'controle',content:'Document DOCX — 2ème Année — Femme et Société'},
 {id:66,name:'Devoir-Travail-2ème-Lentraite-1.doc',type:'DOC',level:'2ème Année',mod:'Contrôle',date:'2025',size:'41 KB',cat:'controle',content:'Document DOC — 2ème Année — Contrôle'},
 {id:67,name:'Dev-synt2-bac-blanc-2021 4L.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Synthèse',date:'2025',size:'35 KB',cat:'synthese',content:'Document DOCX — 3ème Année Lettres — Synthèse'},
 {id:68,name:'Dev-synth1-2ème-nadia1 (2).doc',type:'DOC',level:'2ème Année',mod:'Synthèse',date:'2025',size:'48 KB',cat:'synthese',content:'Document DOC — 2ème Année — Synthèse'},
 {id:69,name:'Dev-synth1-2ème-nadia1 (3).doc',type:'DOC',level:'2ème Année',mod:'Synthèse',date:'2025',size:'48 KB',cat:'synthese',content:'Document DOC — 2ème Année — Synthèse'},
 {id:70,name:'Dev-synth1-2ème-nadia1.doc',type:'DOC',level:'2ème Année',mod:'Synthèse',date:'2025',size:'49 KB',cat:'synthese',content:'Document DOC — 2ème Année — Synthèse'},
 {id:71,name:'Dissertation 2L.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Dissertation',date:'2025',size:'15 KB',cat:'cours',content:'Document DOCX — 3ème Année Lettres — Dissertation'},
 {id:72,name:'dissertation poèsie pratique.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Dissertation',date:'2025',size:'24 KB',cat:'cours',content:'Document DOCX — 3ème Année Lettres — Dissertation'},
 {id:73,name:'dissertation sur la poésie 2.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Poésie',date:'2025',size:'16 KB',cat:'cours',content:'Document DOCX — 3ème Année Lettres — Poésie'},
 {id:74,name:'dissertation sur la poésie 2.pdf',type:'PDF',level:'3ème Année Lettres',mod:'Poésie',date:'2025',size:'40 KB',cat:'cours',content:'Document PDF — 3ème Année Lettres — Poésie'},
 {id:75,name:'dissertation sur la poésie.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Poésie',date:'2025',size:'22 KB',cat:'cours',content:'Document DOCX — 3ème Année Lettres — Poésie'},
 {id:76,name:'dissertation sur la poésie.pdf',type:'PDF',level:'3ème Année Lettres',mod:'Poésie',date:'2025',size:'187 KB',cat:'cours',content:'Document PDF — 3ème Année Lettres — Poésie'},
 {id:77,name:'Document.docx',type:'DOCX',level:'Non classé',mod:'Général',date:'2025',size:'17 KB',cat:'cours',content:'Document DOCX — Non classé — Général'},
 {id:78,name:'elebda3.net-8163 (1).pdf',type:'PDF',level:'Non classé',mod:'Général',date:'2025',size:'869 KB',cat:'cours',content:'Document PDF — Non classé — Général'},
 {id:79,name:'Elle met en parallèle deux réalités pour en faire ressortir des ressemblances ou des différences.docx',type:'DOCX',level:'2ème Année',mod:'Général',date:'2025',size:'89 KB',cat:'cours',content:'Document DOCX — 2ème Année — Général'},
 {id:80,name:'épreuve bac blanc section lettres.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Général',date:'2025',size:'17 KB',cat:'cours',content:'Document DOCX — 3ème Année Lettres — Général'},
 {id:81,name:'epreuve finde session.doc',type:'DOC',level:'2ème Année',mod:'Général',date:'2025',size:'70 KB',cat:'cours',content:'Document DOC — 2ème Année — Général'},
 {id:82,name:'Essai-Partage.doc',type:'DOC',level:'3ème Année Lettres',mod:'Dissertation',date:'2025',size:'34 KB',cat:'cours',content:'Document DOC — 3ème Année Lettres — Dissertation'},
 {id:83,name:'Essai-partage.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Dissertation',date:'2025',size:'16 KB',cat:'cours',content:'Document DOCX — 3ème Année Lettres — Dissertation'},
 {id:84,name:'etude de texte 2ème.docx',type:'DOCX',level:'2ème Année',mod:'Général',date:'2025',size:'24 KB',cat:'cours',content:'Document DOCX — 2ème Année — Général'},
 {id:85,name:'ETUDE DE TEXTE.docx',type:'DOCX',level:'2ème Année',mod:'Général',date:'2025',size:'21 KB',cat:'cours',content:'Document DOCX — 2ème Année — Général'},
 {id:86,name:'évaluation 4ème.docx',type:'DOCX',level:'1ère Année',mod:'Général',date:'2025',size:'28 KB',cat:'evaluation',content:'Document DOCX — 1ère Année — Général'},
 {id:87,name:'Evaluation-formative-la-raison.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Raison et Lumières',date:'2025',size:'14 KB',cat:'cours',content:'Document DOCX — 3ème Année Lettres — Raison et Lumières'},
 {id:88,name:'excel shortcuts.pdf',type:'PDF',level:'Non classé',mod:'Général',date:'2025',size:'468 KB',cat:'cours',content:'Document PDF — Non classé — Général'},
 {id:89,name:'EXCERCICE.docx',type:'DOCX',level:'2ème Année',mod:'Général',date:'2025',size:'29 KB',cat:'exercice',content:'Document DOCX — 2ème Année — Général'},
 {id:90,name:'Exercice 1.docx',type:'DOCX',level:'2ème Année',mod:'Exercice',date:'2025',size:'14 KB',cat:'exercice',content:'Document DOCX — 2ème Année — Exercice'},
 {id:91,name:'exercice 2ème mod 3.docx',type:'DOCX',level:'2ème Année',mod:'Exercice',date:'2025',size:'22 KB',cat:'exercice',content:'Document DOCX — 2ème Année — Exercice'},
 {id:92,name:'Exercice figure de style. 2ème (Enregistré automatiquement).docx',type:'DOCX',level:'2ème Année',mod:'Figures de Style',date:'2025',size:'14 KB',cat:'exercice',content:'Document DOCX — 2ème Année — Figures de Style'},
 {id:93,name:'Exercice figure de style. 2ème.docx',type:'DOCX',level:'2ème Année',mod:'Figures de Style',date:'2025',size:'14 KB',cat:'exercice',content:'Document DOCX — 2ème Année — Figures de Style'},
 {id:94,name:'Exercice figure de style.docx',type:'DOCX',level:'2ème Année',mod:'Figures de Style',date:'2025',size:'13 KB',cat:'exercice',content:'Document DOCX — 2ème Année — Figures de Style'},
 {id:95,name:'exercices nominalisation bac.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Nominalisation',date:'2025',size:'23 KB',cat:'exercice',content:'Document DOCX — 3ème Année Lettres — Nominalisation'},
 {id:96,name:'exercices-la-nominalisation-def.pdf',type:'PDF',level:'3ème Année Lettres',mod:'Nominalisation',date:'2025',size:'2158 KB',cat:'exercice',content:'Document PDF — 3ème Année Lettres — Nominalisation'},
 {id:97,name:'explication de texte p81.docx',type:'DOCX',level:'2ème Année',mod:'Général',date:'2025',size:'13 KB',cat:'cours',content:'Document DOCX — 2ème Année — Général'},
 {id:98,name:'explication mod 4 2ème année.docx',type:'DOCX',level:'2ème Année',mod:'Général',date:'2025',size:'1 KB',cat:'cours',content:'Document DOCX — 2ème Année — Général'},
 {id:99,name:'expression 2ème mod5.docx',type:'DOCX',level:'2ème Année',mod:'Expression',date:'2025',size:'21 KB',cat:'cours',content:'Document DOCX — 2ème Année — Expression'},
 {id:100,name:'expression 4ém mode1 12-2020.docx',type:'DOCX',level:'4ème Année Lettres',mod:'Expression',date:'2025',size:'25 KB',cat:'cours',content:'Document DOCX — 4ème Année Lettres — Expression'},
 {id:101,name:'expression femme et société.doc',type:'DOC',level:'2ème Année',mod:'Femme et Société',date:'2025',size:'34 KB',cat:'cours',content:'Document DOC — 2ème Année — Femme et Société'},
 {id:102,name:'expression librtte.docx',type:'DOCX',level:'2ème Année',mod:'Expression',date:'2025',size:'26 KB',cat:'cours',content:'Document DOCX — 2ème Année — Expression'},
 {id:103,name:'expression mod1 2ème.docx',type:'DOCX',level:'2ème Année',mod:'Expression',date:'2025',size:'28 KB',cat:'cours',content:'Document DOCX — 2ème Année — Expression'},
 {id:104,name:'fiche discours direct.docx',type:'DOCX',level:'4ème Année Lettres',mod:'Discours',date:'2025',size:'26 KB',cat:'fiche',content:'Document DOCX — 4ème Année Lettres — Discours'},
 {id:105,name:'fiche expression 2.docx',type:'DOCX',level:'2ème Année',mod:'Expression',date:'2025',size:'16 KB',cat:'fiche',content:'Document DOCX — 2ème Année — Expression'},
 {id:106,name:'fiche gram mod 4.docx',type:'DOCX',level:'4ème Année Lettres',mod:'Grammaire',date:'2025',size:'15 KB',cat:'fiche',content:'Document DOCX — 4ème Année Lettres — Grammaire'},
 {id:107,name:'fiche la subordination.docx',type:'DOCX',level:'4ème Année Lettres',mod:'Subordination',date:'2025',size:'25 KB',cat:'fiche',content:'Document DOCX — 4ème Année Lettres — Subordination'},
 {id:108,name:'fiche pédagogique mod 4.docx',type:'DOCX',level:'4ème Année Lettres',mod:'Général',date:'2025',size:'16 KB',cat:'fiche',content:'Document DOCX — 4ème Année Lettres — Général'},
 {id:109,name:'Fiche pédagogique.docx',type:'DOCX',level:'2ème Année',mod:'Général',date:'2025',size:'18 KB',cat:'fiche',content:'Document DOCX — 2ème Année — Général'},
 {id:110,name:'fiche texte travail et bien être.docx',type:'DOCX',level:'2ème Année',mod:'Général',date:'2025',size:'16 KB',cat:'fiche',content:'Document DOCX — 2ème Année — Général'},
 {id:111,name:'Fiche-de-lecture-1.docx',type:'DOCX',level:'4ème Année Lettres',mod:'Lecture',date:'2025',size:'16 KB',cat:'fiche',content:'Document DOCX — 4ème Année Lettres — Lecture'},
 {id:112,name:'FICHE-DE-LECTURE-2.docx',type:'DOCX',level:'4ème Année Lettres',mod:'Lecture',date:'2025',size:'13 KB',cat:'fiche',content:'Document DOCX — 4ème Année Lettres — Lecture'},
 {id:113,name:'francais (1).pdf',type:'PDF',level:'3ème Année Lettres',mod:'Général',date:'2025',size:'1882 KB',cat:'cours',content:'Document PDF — 3ème Année Lettres — Général'},
 {id:114,name:'francais.pdf',type:'PDF',level:'3ème Année Lettres',mod:'Général',date:'2025',size:'576 KB',cat:'cours',content:'Document PDF — 3ème Année Lettres — Général'},
 {id:115,name:'francais_c.doc',type:'DOC',level:'3ème Année Lettres',mod:'Général',date:'2025',size:'676 KB',cat:'cours',content:'Document DOC — 3ème Année Lettres — Général'},
 {id:116,name:'francais_c.pdf',type:'PDF',level:'3ème Année Lettres',mod:'Général',date:'2025',size:'523 KB',cat:'cours',content:'Document PDF — 3ème Année Lettres — Général'},
 {id:117,name:'GRAMMAIRE.docx',type:'DOCX',level:'2ème Année',mod:'Grammaire',date:'2025',size:'14 KB',cat:'cours',content:'Document DOCX — 2ème Année — Grammaire'},
 {id:118,name:'Guide_132 a 134.pdf',type:'PDF',level:'Non classé',mod:'Général',date:'2025',size:'590 KB',cat:'cours',content:'Document PDF — Non classé — Général'},
 {id:119,name:'hamdi mned.docx',type:'DOCX',level:'2ème Année',mod:'Général',date:'2025',size:'20 KB',cat:'cours',content:'Document DOCX — 2ème Année — Général'},
 {id:120,name:'image et filtres.docx',type:'DOCX',level:'2ème Année',mod:'Image et Média',date:'2025',size:'24 KB',cat:'cours',content:'Document DOCX — 2ème Année — Image et Média'},
 {id:121,name:'la cause et la conséquence.docx',type:'DOCX',level:'2ème Année',mod:'Rapports Logiques',date:'2025',size:'25 KB',cat:'cours',content:'Document DOCX — 2ème Année — Rapports Logiques'},
 {id:122,name:'le conditionnel 2ème année.docx',type:'DOCX',level:'2ème Année',mod:'Conditionnel',date:'2025',size:'18 KB',cat:'cours',content:'Document DOCX — 2ème Année — Conditionnel'},
 {id:123,name:'Le conformisme bac L.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Conformisme',date:'2025',size:'15 KB',cat:'cours',content:'Document DOCX — 3ème Année Lettres — Conformisme'},
 {id:124,name:'lecture de limage mod 1.docx',type:'DOCX',level:'4ème Année Lettres',mod:'Lecture',date:'2025',size:'119 KB',cat:'cours',content:'Document DOCX — 4ème Année Lettres — Lecture'},
 {id:125,name:'Les Lumières et la raison.doc',type:'DOC',level:'3ème Année Lettres',mod:'Raison et Lumières',date:'2025',size:'37 KB',cat:'cours',content:'Document DOC — 3ème Année Lettres — Raison et Lumières'},
 {id:126,name:'les rapports logiques.docx',type:'DOCX',level:'2ème Année',mod:'Rapports Logiques',date:'2025',size:'16 KB',cat:'cours',content:'Document DOCX — 2ème Année — Rapports Logiques'},
 {id:127,name:'Les types et formes de phrases.docx',type:'DOCX',level:'2ème Année',mod:'Types de Phrases',date:'2025',size:'14 KB',cat:'cours',content:'Document DOCX — 2ème Année — Types de Phrases'},
 {id:128,name:'Liste des professeurs présents à la formation du 4 Avril 2018.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Général',date:'2025',size:'15 KB',cat:'cours',content:'Document DOCX — 3ème Année Lettres — Général'},
 {id:129,name:'Lycée M.docx',type:'DOCX',level:'Non classé',mod:'Général',date:'2025',size:'16 KB',cat:'cours',content:'Document DOCX — Non classé — Général'},
 {id:130,name:'Lycée Secondaire.docx',type:'DOCX',level:'Non classé',mod:'Général',date:'2025',size:'21 KB',cat:'cours',content:'Document DOCX — Non classé — Général'},
 {id:131,name:'Mémoires de l.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Général',date:'2025',size:'20 KB',cat:'cours',content:'Document DOCX — 3ème Année Lettres — Général'},
 {id:132,name:'mireille.doc',type:'DOC',level:'3ème Année Lettres',mod:'Général',date:'2025',size:'2149 KB',cat:'cours',content:'Document DOC — 3ème Année Lettres — Général'},
 {id:133,name:'Module 4.docx',type:'DOCX',level:'4ème Année Lettres',mod:'Général',date:'2025',size:'25 KB',cat:'cours',content:'Document DOCX — 4ème Année Lettres — Général'},
 {id:134,name:'Module I. page de garde.docx',type:'DOCX',level:'4ème Année Lettres',mod:'Général',date:'2025',size:'86 KB',cat:'cours',content:'Document DOCX — 4ème Année Lettres — Général'},
 {id:135,name:'module modernité devoir .docx',type:'DOCX',level:'3ème Année Lettres',mod:'Modernité',date:'2025',size:'28 KB',cat:'controle',content:'Document DOCX — 3ème Année Lettres — Modernité'},
 {id:136,name:'Module poésie.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Poésie',date:'2025',size:'26 KB',cat:'cours',content:'Document DOCX — 3ème Année Lettres — Poésie'},
 {id:137,name:'Module.docx',type:'DOCX',level:'2ème Année',mod:'Général',date:'2025',size:'15 KB',cat:'cours',content:'Document DOCX — 2ème Année — Général'},
 {id:138,name:'Module-dapprentissage-langue-construire-des-explications-la-cause-et-la-conséquence-1.docx',type:'DOCX',level:'2ème Année',mod:'Rapports Logiques',date:'2025',size:'25 KB',cat:'cours',content:'Document DOCX — 2ème Année — Rapports Logiques'},
 {id:139,name:'Niveau.docx',type:'DOCX',level:'Non classé',mod:'Général',date:'2025',size:'26 KB',cat:'cours',content:'Document DOCX — Non classé — Général'},
 {id:140,name:'Niveau1.docx',type:'DOCX',level:'Non classé',mod:'Général',date:'2025',size:'23 KB',cat:'cours',content:'Document DOCX — Non classé — Général'},
 {id:141,name:'Niveau111.docx',type:'DOCX',level:'Non classé',mod:'Général',date:'2025',size:'14 KB',cat:'cours',content:'Document DOCX — Non classé — Général'},
 {id:142,name:'Niveau3.docx',type:'DOCX',level:'Non classé',mod:'Général',date:'2025',size:'26 KB',cat:'cours',content:'Document DOCX — Non classé — Général'},
 {id:143,name:'Nom.docx',type:'DOCX',level:'Non classé',mod:'Général',date:'2025',size:'18 KB',cat:'cours',content:'Document DOCX — Non classé — Général'},
 {id:144,name:'Notification daccord Mme Lamia Gnaba (1).pdf',type:'PDF',level:'Non classé',mod:'Général',date:'2025',size:'171 KB',cat:'cours',content:'Document PDF — Non classé — Général'},
 {id:145,name:'nsibti.docx',type:'DOCX',level:'Non classé',mod:'Général',date:'2025',size:'16 KB',cat:'cours',content:'Document DOCX — Non classé — Général'},
 {id:146,name:'oll-algorithms.pdf',type:'PDF',level:'Non classé',mod:'Général',date:'2025',size:'253 KB',cat:'cours',content:'Document PDF — Non classé — Général'},
 {id:147,name:'Poème Barbara.bac L.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Poésie',date:'2025',size:'15 KB',cat:'cours',content:'Document DOCX — 3ème Année Lettres — Poésie'},
 {id:148,name:'Que les poètes.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Général',date:'2025',size:'20 KB',cat:'cours',content:'Document DOCX — 3ème Année Lettres — Général'},
 {id:149,name:'repartion 2ème année (Enregistré automatiquement).docx',type:'DOCX',level:'2ème Année',mod:'Général',date:'2025',size:'24 KB',cat:'cours',content:'Document DOCX — 2ème Année — Général'},
 {id:150,name:'repartion 2ème année.docx',type:'DOCX',level:'2ème Année',mod:'Général',date:'2025',size:'47 KB',cat:'cours',content:'Document DOCX — 2ème Année — Général'},
 {id:151,name:'répartition 2ème Mod 3.docx',type:'DOCX',level:'2ème Année',mod:'Général',date:'2025',size:'22 KB',cat:'cours',content:'Document DOCX — 2ème Année — Général'},
 {id:152,name:'répartition du module.docx',type:'DOCX',level:'2ème Année',mod:'Général',date:'2025',size:'16 KB',cat:'cours',content:'Document DOCX — 2ème Année — Général'},
 {id:153,name:'révision 2ème.docx',type:'DOCX',level:'2ème Année',mod:'Révision',date:'2025',size:'15 KB',cat:'revision',content:'Document DOCX — 2ème Année — Révision'},
 {id:154,name:'révision bac sc.docx',type:'DOCX',level:'3ème Année Sciences',mod:'Révision',date:'2025',size:'18 KB',cat:'revision',content:'Document DOCX — 3ème Année Sciences — Révision'},
 {id:155,name:'révision compréhension bac sc.docx',type:'DOCX',level:'3ème Année Sciences',mod:'Compréhension',date:'2025',size:'29 KB',cat:'revision',content:'Document DOCX — 3ème Année Sciences — Compréhension'},
 {id:156,name:'Revision du module engagement.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Engagement',date:'2025',size:'19 KB',cat:'revision',content:'Document DOCX — 3ème Année Lettres — Engagement'},
 {id:157,name:'Revision du module Partage (2).docx',type:'DOCX',level:'3ème Année Lettres',mod:'Partage',date:'2025',size:'19 KB',cat:'revision',content:'Document DOCX — 3ème Année Lettres — Partage'},
 {id:158,name:'Revision du module Partage.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Partage',date:'2025',size:'18 KB',cat:'revision',content:'Document DOCX — 3ème Année Lettres — Partage'},
 {id:159,name:'révision finale bas scientifiques.docx',type:'DOCX',level:'3ème Année Sciences',mod:'Révision',date:'2025',size:'18 KB',cat:'revision',content:'Document DOCX — 3ème Année Sciences — Révision'},
 {id:160,name:'Révision module 5.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Révision',date:'2025',size:'22 KB',cat:'revision',content:'Document DOCX — 3ème Année Lettres — Révision'},
 {id:161,name:'subordination 4e L.docx',type:'DOCX',level:'4ème Année Lettres',mod:'Subordination',date:'2025',size:'1998 KB',cat:'cours',content:'Document DOCX — 4ème Année Lettres — Subordination'},
 {id:162,name:'subordination 4e L.pdf',type:'PDF',level:'4ème Année Lettres',mod:'Subordination',date:'2025',size:'527 KB',cat:'cours',content:'Document PDF — 4ème Année Lettres — Subordination'},
 {id:163,name:'Tableau_figures_de_style.docx',type:'DOCX',level:'2ème Année',mod:'Général',date:'2025',size:'17 KB',cat:'cours',content:'Document DOCX — 2ème Année — Général'},
 {id:164,name:'test dia 1ère.docx',type:'DOCX',level:'1ère Année',mod:'Général',date:'2025',size:'28 KB',cat:'evaluation',content:'Document DOCX — 1ère Année — Général'},
 {id:165,name:'test diagnostique 1ère.docx',type:'DOCX',level:'1ère Année',mod:'Général',date:'2025',size:'23 KB',cat:'evaluation',content:'Document DOCX — 1ère Année — Général'},
 {id:166,name:'test diagnostique 3ème.docx',type:'DOCX',level:'1ère Année',mod:'Général',date:'2025',size:'23 KB',cat:'evaluation',content:'Document DOCX — 1ère Année — Général'},
 {id:167,name:'text002.pdf',type:'PDF',level:'3ème Année Lettres',mod:'Général',date:'2025',size:'2243 KB',cat:'cours',content:'Document PDF — 3ème Année Lettres — Général'},
 {id:168,name:'text003.pdf',type:'PDF',level:'3ème Année Lettres',mod:'Général',date:'2025',size:'478 KB',cat:'cours',content:'Document PDF — 3ème Année Lettres — Général'},
 {id:169,name:'text004.pdf',type:'PDF',level:'3ème Année Lettres',mod:'Général',date:'2025',size:'339 KB',cat:'cours',content:'Document PDF — 3ème Année Lettres — Général'},
 {id:170,name:'texte 1ère année mod 5.docx',type:'DOCX',level:'1ère Année',mod:'Général',date:'2025',size:'14 KB',cat:'cours',content:'Document DOCX — 1ère Année — Général'},
 {id:171,name:'texte bac blanc.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Général',date:'2025',size:'13 KB',cat:'cours',content:'Document DOCX — 3ème Année Lettres — Général'},
 {id:172,name:'texte la pollution.docx',type:'DOCX',level:'2ème Année',mod:'Environnement',date:'2025',size:'13 KB',cat:'cours',content:'Document DOCX — 2ème Année — Environnement'},
 {id:173,name:'texte mod 1.docx',type:'DOCX',level:'4ème Année Lettres',mod:'Général',date:'2025',size:'13 KB',cat:'cours',content:'Document DOCX — 4ème Année Lettres — Général'},
 {id:174,name:'Texte pollution 2.docx',type:'DOCX',level:'2ème Année',mod:'Environnement',date:'2025',size:'17 KB',cat:'cours',content:'Document DOCX — 2ème Année — Environnement'},
 {id:175,name:'Tonalités-ou-registres.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Tonalités',date:'2025',size:'185 KB',cat:'cours',content:'Document DOCX — 3ème Année Lettres — Tonalités'},
 {id:176,name:'Tradition et modernité mod 3.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Modernité',date:'2025',size:'17 KB',cat:'cours',content:'Document DOCX — 3ème Année Lettres — Modernité'},
 {id:177,name:'Versification et formes poétiques.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Poésie',date:'2025',size:'29 KB',cat:'cours',content:'Document DOCX — 3ème Année Lettres — Poésie'},
 {id:178,name:'vocab 2ème mod3.docx',type:'DOCX',level:'2ème Année',mod:'Vocabulaire',date:'2025',size:'22 KB',cat:'vocabulaire',content:'Document DOCX — 2ème Année — Vocabulaire'},
 {id:179,name:'vocab mod 2.docx',type:'DOCX',level:'2ème Année',mod:'Vocabulaire',date:'2025',size:'16 KB',cat:'vocabulaire',content:'Document DOCX — 2ème Année — Vocabulaire'},
 {id:180,name:'vocabulaire-4ème-L.docx',type:'DOCX',level:'3ème Année Lettres',mod:'Vocabulaire',date:'2025',size:'15 KB',cat:'vocabulaire',content:'Document DOCX — 3ème Année Lettres — Vocabulaire'}
];
